image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - name: Run App
    init: python3 -m pip install -r requirements.txt
    command: flask run --host 0.0.0.0
  - name: Test
    init: python3 -m pip install -r requirements.txt
    command: python3 -m pytest -v